version: "3.9"
services:
  elasticsearch:
    image: elasticsearch:8.12.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    volumes:
      - ./deploy/esdata:/usr/share/elasticsearch/data
    # helth curl -s http://127.0.0.1:9200/_cluster/health
    # indexes curl http://127.0.0.1:9200/_cat/indices/ 

  kibana:
    image: kibana:8.12.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200 

  logstash:
    image: logstash:8.12.2
    user: root #сменил дефолтного юзера на рута
    environment:
       
      ES_HOST: "elasticsearch:9200"
    ports:
      - "5044:5044/udp"
    volumes:
      - ./configs/logstash/config.yml:/usr/share/logstash/config/logstash.yml
      - ./configs/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./configs/logstash/pipelines:/usr/share/logstash/config/pipelines
      - ./nginxlog:/usr/share/logstash/nginx
    depends_on:
          - elasticsearch
          - nginx
    
  nginx:
    image: nginx:1.25
    ports:
      - 80:80
    volumes:
      - ./nginxlog:/var/log/nginx 
    restart: always